appName: be-places
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__places
  tag: 0.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 2

secrets:
  env:
    secretsEnv:
      PF_HOST_PORT: "80"

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

ingress:
  tls:
    secret: internal-secret-tls