appName: be-esignatures-e-sign-co-uk
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__esignatures_e_sign_co_uk
  tag: 0.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  scylladb_credentials:
      PF_SCYLLA_USERNAME: USERNAME
      PF_SCYLLA_PASSWORD: PASSWORD

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  ingress:
    host: "" 
    tls:
      secret: internal-secret-tls
  scylladb:
    PF_SCYLLA_HOSTS: SCYLLA_SERVERS
    PF_SCYLLA_REPLICATION_STRATEGY: SCYLLA_REPLICATION_STRATEGY
    PF_SCYLLA_TIMEOUT: SCYLLA_TIMEOUT
    PF_SCYLLA_CONNECT_TIMEOUT: SCYLLA_CONNECT_TIMEOUT