appName: be-financial-events
replicasCount: 1

containers:
  protocol: TCP
  containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__financial_events
  tag: 1.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

secrets:
  scylladb_credentials:
    PF_SCYLLA_USERNAME: USERNAME
    PF_SCYLLA_PASSWORD: PASSWORD
  redis:
    PF_REDIS_PASSWORD: PASSWORD

configMaps:
  env:
    PF_HOST_PORT: "0.0.0.0:8080"
  ingress:
    host: ""
    tls:
      secret: internal-secret-tls
  redis:
    PF_REDIS_HOST: REDIS_SERVER
    PF_REDIS_NAMESPACE_SEPARATOR: REDIS_SEPARATOR
  scylladb:
    PF_SCYLLA_HOSTS: SCYLLA_SERVERS
    PF_SCYLLA_REPLICATION_STRATEGY: SCYLLA_REPLICATION_STRATEGY
    PF_SCYLLA_TIMEOUT: SCYLLA_TIMEOUT
    PF_SCYLLA_CONNECT_TIMEOUT: SCYLLA_CONNECT_TIMEOUT
    PF_SCYLLA_SSL: SCYLLA_SSL
  kafka_servers:
    PF_KAFKA_SERVERS: KAFKA_SERVERS
    PF_KAFKA_OFFSET: KAFKA_OFFSET
