apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
     {{- with .Values.global.kibana }}
    - hosts:
        - {{ .ingress.host }}
      secretName: app-secret-tls
  rules:
  - host: {{ .ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .name }}
          servicePort: {{ .port }}
        path: /(.*)
    {{- end }}