appName: be-nashville
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 443

service:
  type: ClusterIP
  port: 443
  targetPort: 443

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__nashville
  tag: 0.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  secretsJwt:
    PF_JWT_PRIVATE_KEY: ""
    PF_JWT_PUBLIC_KEY: ""
  postgresdb_credentials:
    PF_POSTGRES_ENCRYPTION_KEY: ENCRYPTION_KEY
      
tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

secrets:
  scylladb_credentials:
      PF_SCYLLA_USERNAME: USERNAME
      PF_SCYLLA_PASSWORD: PASSWORD

configMaps:
  env:
    PF_HOST_PORT: "0.0.0.0:443"
    PF_DEBUG: "0"
    PF_SERVICE_NAME: "be__nashville"
    PF_GRPC_HOST: "0.0.0.0"
    PF_GRPC_PORT: "443"
    PF_REST_HOST: "0.0.0.0"
    PF_REST_PORT: "80"
    PF_GRPC_EXTERNAL_PORT: "443"
    PF_DATABASE_POOL_MAX_SIZE: "10"
    PF_DATABASE_POOL_MIN_SIZE: "10"
  server:
    PF_HOST_PORT: GRPC_SSL_HOST_PORT
    PF_API_KEY_HEADER_AUTHORIZATION: API_KEY_HEADER_AUTHORIZATION
    PF_JWT_EXPIRATION_TIME_IN_MINUTES: JWT_EXPIRATION_TIME_IN_MINUTES
    PF_JWT_AUTHORIZATION: JWT_AUTHORIZATION
  ingress:
    host: "" 
    tls:
      secret: internal-secret-tls
  scylladb:
    PF_SCYLLA_HOSTS: SCYLLA_SERVERS
    PF_SCYLLA_REPLICATION_STRATEGY: SCYLLA_REPLICATION_STRATEGY
    PF_SCYLLA_TIMEOUT: SCYLLA_TIMEOUT
    PF_SCYLLA_CONNECT_TIMEOUT: SCYLLA_CONNECT_TIMEOUT
  kafka_servers: 
    PF_KAFKA_SERVERS: KAFKA_SERVERS
    PF_KAFKA_OFFSET: KAFKA_OFFSET

