appName: be-affordability
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__affordability
  tag: 1.2.3
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 2

secrets:
  env:

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  env:
    PF_HOST_PORT: 80
  database:
    PF_DATABASE_HOSTNAME: HOSTNAME
    PF_DATABASE_PORT: PORT
    PF_DATABASE_SSL_MODE: SSL_MODE
  ingress:
    host: ""
