apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    nginx.ingress.kubernetes.io/grpc-web: 'True'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  {{- with .Values}}
  tls:
    - hosts:
      - {{ .configMaps.ingress.host }}
      secretName: {{ .configMaps.ingress.tls.secret }}
  rules:
  - host: {{ .configMaps.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .appName }}-svc
          servicePort: {{ .service.port }}
        path: /(.*)
  {{- end }}