appName: be-statements
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 8443

service:
  type: ClusterIP
  port: 8443
  targetPort: 8443

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__statements
  tag: 1.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  scylladb_credentials:
      PF_SCYLLA_USERNAME: USERNAME
      PF_SCYLLA_PASSWORD: PASSWORD
  redis:
    PF_REDIS_PASSWORD: PASSWORD

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  env:
    PF_HOST_PORT: 8443
  ingress:
    host: ""
  redis:
    PF_REDIS_HOST: REDIS_SERVER
    PF_REDIS_NAMESPACE_SEPARATOR: REDIS_SEPARATOR
  scylladb:
    PF_SCYLLA_HOSTS: SCYLLA_SERVERS
    PF_SCYLLA_TIMEOUT: SCYLLA_TIMEOUT
    PF_SCYLLA_CONNECT_TIMEOUT: SCYLLA_CONNECT_TIMEOUT
    PF_SCYLLA_SSL: SCYLLA_SSL
    PF_SCYLLA_ENCRYPTION_KEY: SCYLLA_ENCRYPTION_KEY
  kafka_servers: 
    PF_KAFKA_SERVERS: KAFKA_SERVERS
    PF_KAFKA_OFFSET: KAFKA_OFFSET 
