appName: be-statements
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 443

service:
  type: ClusterIP
  port: 443
  targetPort: 443

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__statements
  tag: 0.0.10
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  scylladb_credentials:
      PF_SCYLLA_USERNAME: USERNAME
      PF_SCYLLA_PASSWORD: PASSWORD

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  env:
    PF_HOST_PORT: 443
  ingress:
    host: "" 
  scylladb:
    PF_SCYLLA_HOSTS: SCYLLA_SERVERS
    PF_SCYLLA_TIMEOUT: SCYLLA_TIMEOUT
    PF_SCYLLA_CONNECT_TIMEOUT: SCYLLA_CONNECT_TIMEOUT
    PF_SCYLLA_SSL: SCYLLA_SSL
    PF_SCYLLA_ENCRYPTION_KEY: SCYLLA_ENCRYPTION_KEY
  kafka_servers: 
    PF_KAFKA_SERVERS: KAFKA_SERVERS
    PF_KAFKA_OFFSET: KAFKA_OFFSET 
