appName:
replicasCount: 1

containers:
  protocol: TCP
  containerPort: 8080

pfenv: unset

service:
  rest:
    type: ClusterIP
    port: 80
    targetPort: 8080

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__cle_api
  tag: 0.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  ingress:
    rest:
      host: "cle-api-pf-dev.services.dev.premfina.com"
      tls:
        secret: services-secret-tls
