# Must be set to 1 because CONNECT_REST_ADVERTISED_HOST_NAME is used to get to the leader of the kafka connect cluster
# (i.e specific pod) but is currently pointing to the ingress
replicasCount: 1

containers:
  protocol: TCP
  containerPort: 8083

service:
  type: ClusterIP
  port: 80
  targetPort: 8083

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/infrastructure
  repository: be__kafka_connect
  tag: 1.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

configMaps:
  ingress:
    host: kafka-connect.internal.premfina.com
    tls:
      secret: internal-secret-tls
  env:
    CONNECT_REST_PORT: 8083
    CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
    CONNECT_REST_ADVERTISED_HOST_NAME: be-kafka-connect-svc
    CONNECT_GROUP_ID: kafka-connect-group-1
    CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect-configs-1
    CONNECT_CONFIG_STORAGE_CLEANUP_POLICY: "compact"
    CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect-offsets-1
    CONNECT_OFFSET_STORAGE_CLEANUP_POLICY: "compact"
    CONNECT_STATUS_STORAGE_TOPIC: kafka-connect-status-1
    CONNECT_STATUS_STORAGE_CLEANUP_POLICY: "compact"
    CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
    CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://be-kafka-schema-registry-svc
    CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
    CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://be-kafka-schema-registry-svc
    CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
    CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "2"
    CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "2"
    CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "2"
