apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  {{- with .Values}}
    - hosts:
        - {{ .configMaps.ingress.grpc.host }}
      secretName: {{ .configMaps.ingress.grpc.tls.secret }}
  rules:
  - host: {{ .configMaps.ingress.grpc.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .appName }}-svc
          servicePort: {{ .service.grpc.port }}
        path: /(.*)
  {{- end }}