kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
{{- with .Values }}
  name: {{ .appName }}-svc
spec:
  selector:
    app: {{ .appName }}
  {{- with .service }}
  type: {{ .type }}
  ports:
    - name: grpc
      port: {{ .grpc.port }}
      targetPort: {{ .grpc.targetPort }}
    - name: rest
      port: {{ .rest.port }}
      targetPort: {{ .rest.targetPort }}
  {{- end }}
{{- end }}