appName: be-db-identities
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 443

service:
  type: ClusterIP
  port: 443
  targetPort: 443

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__db_identities
  tag: 0.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  postgresdb_credentials:
      PF_POSTGRES_ENCRYPTION_KEY: ENCRYPTION_KEY
      PF_POSTGRES_HOST_PORT: HOST_PORT
      PF_POSTGRES_USERNAME: USERNAME
      PF_POSTGRES_PASSWORD: PASSWORD
      PF_POSTGRES_SSL: SSL
      PF_POSTGRES_MICROSERVICES_HOST_PORT: MS_HOST_PORT
      PF_POSTGRES_MICROSERVICES_USERNAME: MS_USERNAME
      PF_POSTGRES_MICROSERVICES_PASSWORD: MS_PASSWORD
      PF_POSTGRES_MICROSERVICES_SSL: SSL
      PF_POSTGRES_MICROSERVICES_USERNAME_SUFFIX: SUFFIX
      PF_POSTGRES_MAX_CLIENTS_PER_SCHEMA: MAX_CLIENTS
      PF_POSTGRES_MICROSERVICES_NAME: MS_DB_NAME

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  server:  
    PF_HOST_PORT: GRPC_SSL_HOST_PORT
  ingress:
    host: ""
    tls:
      secret: internal-secret-tls