appName: be-bank-checker-experian
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 8080

service:
  rest:
    type: ClusterIP
    port: 8080
    targetPort: 8080

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__bank_checker_experian
  tag: 0.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  scylladb_credentials:
      PF_SCYLLA_USERNAME: USERNAME
      PF_SCYLLA_PASSWORD: PASSWORD
      
tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  server:
    PF_REST_HOST_PORT: REST_HOST_PORT
  ingress:
    rest:
      host: ""
      tls:
        secret: services-secret-tls
  scylladb:
    PF_SCYLLA_HOSTS: SCYLLA_SERVERS
    PF_SCYLLA_REPLICATION_STRATEGY: SCYLLA_REPLICATION_STRATEGY
    PF_SCYLLA_TIMEOUT: SCYLLA_TIMEOUT
    PF_SCYLLA_CONNECT_TIMEOUT: SCYLLA_CONNECT_TIMEOUT