appName: prometheus
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 9090

service:
  type: ClusterIP
  port: 80
  targetPort: 9090

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: sys__prometheus
  tag: latest
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1


configMaps:
  prometheus_global:
    scrape_interval: 15s
    evaluation_interval: 15s

  prometheus_local:
    job_name: prometheus_local
    env: local
    target: "localhost:9090"

  prometheus:
    job_name: kafka_dev
    env: dev
    target1: "10.6.5.6:9102"
    target2: "10.6.5.6:9103"
    target3: ""

  ingress:
    host: prometheus.internal.dev.premfina.com
    tls:
      secret: services-secret-tls


      