apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-rest-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    cle: cle-api
    pfenv: {{ .Values.pfenv }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
spec:
  tls:
    - hosts:
        - {{ .Values.configMaps.ingress.rest.host }}
      secretName: {{ .Values.configMaps.ingress.rest.tls.secret }}
  rules:
  - host: {{ template "REST_INGRESS" . }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-svc
            port:
              number: {{ .Values.service.rest.port }}
        path: /
        pathType: Prefix
  