apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
{{- with .Values }}
  replicas: {{ .replicasCount }}
  strategy:
    type: {{ .updateStrategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .updateStrategy.maxUnavailable }}
      maxSurge: {{ .updateStrategy.maxSurge }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
{{- with .Values.image }}
          image: {{ .registry }}/{{ .repository }}:{{ .tag }}
          imagePullPolicy: {{ .policy }}
{{- end }}
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
          env:
           {{- include "SET_ENV_CONFIGS" . | indent 12 }}
            - name: CONNECT_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-servers-configmap
                  key: KAFKA_SERVERS
          ports:
{{- with .Values }}
            - containerPort:  {{ .containers.containerPort }}
              protocol: {{ .containers.protocol | quote }}
 {{- end }}
 