
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.appName }}-{{ .Values.pfEnv }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values }}
  replicas: {{ .replicasCount }}
  strategy:
    {{- with .updateStrategy }}
    type: {{ .type }}
    rollingUpdate:
      maxUnavailable: {{ .maxUnavailable }}
      maxSurge: {{ .maxSurge }}
    {{- end }}  
  selector:
    matchLabels:
      app: {{ .appName }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
        pfenv: {{ .pfEnv }}
  {{- end }}
    spec:
      containers:
        - env:
          {{- include "CERT_TLS_FILE_NAMES" . | indent 12 }}
          {{- include "SET_REDIS_SECRET" . | indent 12 }}
          {{- include "EXPORT_REDIS_CONFIGMAP" . | indent 12 }}
          {{- include "SET_ORACLE_SECRET" . | indent 12 }}
          {{- include "EXPORT_ORACLE_CONFIGMAP" . | indent 12 }}
          {{- include "EXPORT_KAFKA_SERVERS_CONFIGMAP" . | indent 12 }}
          {{- include "EXPORT_KAFKA_TOPICS" . | indent 12 }}
          {{- include "EXPORT_ENV_CONFIGS" . | indent 12 }}
          name: {{ .Values.appName }}
          image: {{ template "SET_DOCKER_IMAGE" . }}
          {{- with .Values }}
          imagePullPolicy: {{ .image.policy }}
          ports:
            - containerPort:  {{ .containers.containerPort }}
              protocol: {{ .containers.protocol | quote }}
          volumeMounts:
            - name: app-tls
              mountPath: "/app/cert"
              readOnly: true
            
            - name: cle-oracle-pf-tnsnames
              mountPath: {{ .configMaps.env.TNS_ADMIN }}
          {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
      volumes:
      - name: app-tls
        secret:
          secretName: {{ template "CERT_TLS_SECRET_NAME" . }}
       
      - name: cle-oracle-pf-tnsnames
        secret:
          secretName: cle-oracle-pf-tnsnames
