apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: kong-istio
  name: {{ .Values.appName }}-certificate
spec:
  secretName: {{ template "CERT_TLS_SECRET_NAME" . }}
  issuerRef:
    name: issuer-ca
    kind: Issuer
  commonName: "{{ .Values.appName }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
    - Premfina {{ .Release.Namespace }}
  dnsNames:
    - "{{ .Values.appName }}"
    - "{{ .Values.appName }}-svc"
    - "{{ .Values.appName }}-svc.{{ .Release.Namespace }}"
    - "{{ .Values.appName }}-svc.{{ .Release.Namespace }}.svc"
    - "{{ .Values.appName }}-svc.{{ .Release.Namespace }}.svc.cluster"
    - "{{ .Values.appName }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
    - "localhost"