apiVersion: v1
kind: Service
metadata:
  namespace: kong
  name: {{ .Values.appName }}-svc
  annotations:
    konghq.com/protocols: grpcs
spec:
{{- with .Values }}
  selector:
    app: {{ .appName }}
  {{- with .service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}    
{{- end }}