appName: be-cra
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 443

service:
  type: ClusterIP
  port: 443
  targetPort: 443

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__cra
  tag: 1.7.1
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  postgresql_credentials:
    PF_POSTGRES_USER: USERNAME
    PF_POSTGRES_PASSWORD: PASSWORD

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

# To be replaced by the actual environment variables loaded on the deployment scripts
volume:
  name: dev-system-files
  path: /mnt/pfdevukfilestorage

configMaps:
  services:
    PF_ENVIRONMENT: PF_ENVIRONMENT_NAME
    CRA_CREDIT_SAFE_BASE_URL: PF_CRA_CREDIT_SAFE_SERVICE_HOSTNAME
    CRA_EXPERIAN_BASE_URL: PF_CRA_EXPERIAN_SERVICE_HOSTNAME
    PF_CRA_LEXIS_NEXIS_SERVICE_HOSTNAME: PF_AGREEMENT_FILES_SERVICE_HOSTNAME
    BE_DATA_FETCHER_ORACLE_HOST: PF_DATA_FETCHER_ORACLE_SERVICE_HOSTNAME
    BE_BANK_CHECKER_HOST: PF_BANK_CHECKER_SERVICE_HOSTNAME
    BE__AFFORDABILITY_HOST: PF_AFFORDABILITY_SERVICE_HOSTNAME
    PF_ID_UPLOAD_HOST: PF_ID_UPLOAD_SERVICE_HOSTNAME
  env:
    PF_HOST_PORT: 443
    PF_REPORT_GENERATION_TEMP_STORAGE_PATH: /temp
  paths:
    PF_FILE_STORAGE_PATH: PF_CRA_REPORT_SHARED_STORAGE_PATH
  ingress:
    host: ""
  postgresql:
    PF_POSTGRES_HOST: HOSTNAME
    PF_POSTGRES_PORT: PORT
    PF_POSTGRES_SSL_MODE: SSL_MODE
    PF_DATABASE_DEBUG: DEBUG_MODE
