appName: fe-portal
replicasCount: 1

containers:
  protocol: TCP
  containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/frontend
  # registry: premfinaukcontainerregistry.azurecr.io/docker/frontend
  repository: fe__portal
  tag: 0.1.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

configMaps:
  api:
    url: "https://be-bff-portal.services.dev.premfina.com"
  restApi:
    url: "https://be-bff-portal-rest.services.dev.premfina.com/v1"
  ingress:
    host: hub.dev.premfina.com
    tls:
      secretName: services-secret-tls

