appName: be-id-upload
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 8443

service:
  type: ClusterIP
  port: 8443
  targetPort: 8443

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__id_upload
  tag: 1.5.1
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  scylladb_credentials:
    PF_SCYLLA_USERNAME: USERNAME
    PF_SCYLLA_PASSWORD: PASSWORD
  yoti:
    PF_YOTI_PRIVATE_KEY: YOTI_PRIVATE_KEY
    PF_YOTI_CLIENT_SDK_ID: YOTI_CLIENT_SDK_ID
  bitly:
    PF_BITLY_TOKEN: BITLY_TOKEN
    PF_BITLY_GROUP_GUID: BITLY_GROUP_GUID


tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  env:
    PF_HOST_PORT: 8443
    PF_EMAIL_HANDLER_HOST: http://be-email.internal.dev.premfina.com
    PF_SMS_HANDLER_HOST: http://10.6.0.5:8051
    PF_FILE_MANAGER_HOST: http://be-file-manager.internal.dev.premfina.com
    PF_AGREEMENT_FILES_HOST: http://10.6.0.5:8017
    PF_YOTI_WEBHOOK_ENDPOINT: https://be-gateway.internal.dev.premfina.com/v1/session/complete
  ingress:
    host: ""
  scylladb:
    PF_SCYLLA_HOSTS: SCYLLA_SERVERS
    PF_SCYLLA_TIMEOUT: SCYLLA_TIMEOUT
    PF_SCYLLA_CONNECT_TIMEOUT: SCYLLA_CONNECT_TIMEOUT
    PF_SCYLLA_SSL: SCYLLA_SSL
    PF_SCYLLA_ENCRYPTION_KEY: SCYLLA_ENCRYPTION_KEY
    PF_SCYLLA_DEFAULT_PAGE_SIZE: SCYLLA_DEFAULT_PAGE_SIZE
  kafka_servers:
    PF_KAFKA_SERVERS: KAFKA_SERVERS
    PF_KAFKA_OFFSET: KAFKA_OFFSET
