appName: be-id-upload
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 8443

service:
  type: ClusterIP
  port: 8443
  targetPort: 8443

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__id_upload
  tag: 1.5.1
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

secrets:
  scylladb_credentials:
    PF_SCYLLA_USERNAME: USERNAME
    PF_SCYLLA_PASSWORD: PASSWORD
  yoti:
    PF_YOTI_PRIVATE_KEY: YOTI_PRIVATE_KEY
    PF_YOTI_CLIENT_SDK_ID: YOTI_CLIENT_SDK_ID
  bitly:
    PF_BITLY_TOKEN: BITLY_TOKEN
    PF_BITLY_GROUP_GUID: BITLY_GROUP_GUID


tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

configMaps:
  services:
    PF_EMAIL_HANDLER_HOST: PF_EMAIL_SERVICE_HOSTNAME
    PF_SMS_HANDLER_HOST: PF_SMS_SERVICE_HOSTNAME
    PF_FILE_MANAGER_HOST: PF_FILE_MANAGER_SERVICE_HOSTNAME
    PF_AGREEMENT_FILES_HOST: PF_AGREEMENT_FILES_SERVICE_HOSTNAME
  external_env:
    PF_YOTI_WEBHOOK_ENDPOINT: PF_YOTI_WEBHOOK_ENDPOINT
  env:
    PF_HOST_PORT: 8443
  ingress:
    host: ""
  scylladb:
    PF_SCYLLA_HOSTS: SCYLLA_SERVERS
    PF_SCYLLA_TIMEOUT: SCYLLA_TIMEOUT
    PF_SCYLLA_CONNECT_TIMEOUT: SCYLLA_CONNECT_TIMEOUT
    PF_SCYLLA_SSL: SCYLLA_SSL
    PF_SCYLLA_ENCRYPTION_KEY: SCYLLA_ENCRYPTION_KEY
    PF_SCYLLA_DEFAULT_PAGE_SIZE: SCYLLA_DEFAULT_PAGE_SIZE
  kafka_servers:
    PF_KAFKA_SERVERS: KAFKA_SERVERS
    PF_KAFKA_OFFSET: KAFKA_OFFSET
