apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicasCount }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.maxSurge }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - env:
          {{- include "CERT_TLS_FILE_NAMES" . | indent 12 }}
          {{- include "LIST_ENV_VARIABLES" . | indent 12 }}
          name: {{ .Values.appName }}
          image: {{ template "SET_DOCKER_IMAGE" . }}
          imagePullPolicy: {{ .Values.image.policy }}
          ports:
            - containerPort:  {{ .Values.containers.containerPort }}
              protocol: {{ .Values.containers.protocol | quote }}
          volumeMounts:
            - mountPath: "/app/cert"
              name: app-tls
              readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: {{ template "CERT_TLS_SECRET_NAME" . }}