apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Values.environment }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - {{ .Values.host.name }}
      secretName: {{ .Values.ingress.tls.secret }}
  rules:
  - host: {{ .Values.host.name }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.appName }}-svc
          servicePort: {{ .Values.service.port }}
        path: /(.*)
