apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ .Values.appName }}-{{ .Values.pfEnv }}-certificate"
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ template "CERT_TLS_SECRET_NAME" . }}
  issuerRef:
    name: issuer-ca
    kind: Issuer
  commonName: "{{ .Values.appName }}-{{ .Values.pfEnv }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
    - Premfina {{ .Release.Namespace }}
  dnsNames:
    - "{{ .Values.appName }}-{{ .Values.pfEnv }}"
    - "{{ .Values.appName }}-{{ .Values.pfEnv }}-svc"
    - "{{ .Values.appName }}-{{ .Values.pfEnv }}-svc.{{ .Release.Namespace }}"
    - "{{ .Values.appName }}-{{ .Values.pfEnv }}-svc.{{ .Release.Namespace }}.svc"
    - "{{ .Values.appName }}-{{ .Values.pfEnv }}-svc.{{ .Release.Namespace }}.svc.cluster"
    - "{{ .Values.appName }}-{{ .Values.pfEnv }}-svc.{{ .Release.Namespace }}.svc.cluster.local"
    - "localhost"
