replicasCount: 2

containers:
  protocol: TCP
  containerPort: 3000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/infrastructure
  repository: sys__grafana
  tag: 1.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

configMaps:
  ingress:
    host: grafana.internal.dev.premfina.com
    tls:
      secret: internal-secret-tls
