apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  env.json: |
    {
      "apiURL": "{{ .Values.configMaps.api.url }}"
    }
