apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  env.json: |
    {
      "apiURL": "{{ .Values.configMaps.url.envoy }}"
    }
