apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fe-portal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # cert-manager.io/cluster-issuer: "letsencrypt-dev"
{{- with .Values }}
spec:
  tls:
    - hosts:
        - {{ .ingress.host }}
      secretName: services-staging-tls
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - backend:
              serviceName: fe-portal-svc
              servicePort: 80
            path: /(.*)
{{- end}}