apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}
{{- with .Values }}
  {{- with .service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}    
{{- end }}