apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values }}
  replicas: {{ .replicasCount }}
  strategy:
    {{- with .updateStrategy }}
    type: {{ .type }}
    rollingUpdate:
      maxUnavailable: {{ .maxUnavailable }}
      maxSurge: {{ .maxSurge }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ .appName }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
  {{- end }}
    spec:
      containers:
        - env:
          {{- include "SET_ENV_SECRETS" . | indent 12 }}
          {{- include "CERT_TLS_FILE_NAMES" . | indent 12 }}
          {{- include "EXPORT_ENV_CONFIGS" . | indent 12 }}
          name: {{ .Values.appName }}
          image: {{ template "SET_DOCKER_IMAGE" . }}
          imagePullPolicy: {{ .Values.image.policy }}
          ports:
            - containerPort:  {{ .Values.containers.containerPort }}
              protocol: {{ .Values.containers.protocol | quote }}
          volumeMounts:
            - mountPath: "/app/cert"
              name: app-tls
              readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: {{ template "CERT_TLS_SECRET_NAME" . }}