kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
        scrape_interval: {{ .Values.configMaps.prometheus_global.scrape_interval }}
        evaluation_interval: {{ .Values.configMaps.prometheus_global.evaluation_interval }}

    scrape_configs:
      - job_name: {{ .Values.configMaps.prometheus_local.job_name }}

        static_configs:
        - targets: 
            - "{{ .Values.configMaps.prometheus_local.target }}"
          labels:
            env: {{ .Values.configMaps.prometheus_local.env }}


      - job_name: {{ .Values.configMaps.prometheus.job_name }}
        static_configs:
        - targets:
            - "{{ .Values.configMaps.prometheus.target1 }}"
            - "{{ .Values.configMaps.prometheus.target2 }}"
            - "{{ .Values.configMaps.prometheus.target3 }}"
            - "{{ .Values.configMaps.prometheus.target4 }}"
          labels:
            env: {{ .Values.configMaps.prometheus.env }}

