appName: be-web-sockets
replicasCount: 2

containers:
  protocol: TCP
  containerPort: 8443

service:
  type: ClusterIP
  port: 8443
  targetPort: 8443

image:
  registry: premfinaukcontainerregistry.azurecr.io/docker/backend
  repository: be__web_sockets
  tag: 0.0.0
  policy: Always

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 10%
  maxSurge: 1

tls:
  files:
    PF_TLS_CA_FILE: /app/cert/ca.crt
    PF_TLS_CRT_FILE: /app/cert/tls.crt
    PF_TLS_KEY_FILE: /app/cert/tls.key

secrets:
  secretsJwt:
    PF_JWT_PUBLIC_KEY: /app/jwt/PF_JWT_PUBLIC_KEY

configMaps:
  server:  
    PF_HOST_PORT: REST_SSL_HOST_PORT
    PF_JWT_AUTHORIZATION: JWT_AUTHORIZATION
  ingress:
    host: "" 
    tls:
      secret: internal-secret-tls
  kafka_servers: 
    PF_KAFKA_SERVERS: KAFKA_SERVERS
    PF_KAFKA_OFFSET: KAFKA_OFFSET 