apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.global.kibana }}
    app: {{ .name }}
spec:
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
  selector:
    app: {{ .name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- with .Values.global.kibana }}
    app: {{ .name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
      {{- end }}
        image: docker.elastic.co/kibana/kibana:7.10.1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          {{- with .Values.global.elasticsearch }}
          - name: ELASTICSEARCH_HOSTS
            value: "{{ .scheme }}://{{ .host }}:{{ .port }}"
        ports:
        {{- end }}
        - containerPort: {{ .Values.global.kibana.port }}